var bingoList = [];
bingoList[1] = [
  { name: "First stream in 7+ days", types: ["normal"]},
  { name: "3+ streams in 7 days", types: ["normal"]},
  { name: "Amazon suggestions", types: ["normal"]},
  { name: "Opening Hold On screens last 10+ minutes", types: ["normal"]},
  { name: "Cholera", types: ["normal"]},
  { name: "Mr. Bones", types: ["normal"]},
  { name: "Persona reference", types: ["normal"]},
  { name: "Ace Attorney reference", types: ["normal"]},
  { name: "Sonic the Hedgehog reference", types: ["normal"]},
  { name: "'I'm sorry, what!?'", types: ["normal"]},
  { name: "Tim refers to himself as a girl", types: ["normal"]},
  { name: "Tim mimics a character", types: ["normal"]},
  { name: "PICNIC", types: ["normal"]},
  { name: "Tim uses the printer", types: ["normal"]},
  { name: "Game isn't installed yet or requires an update", types: ["normal"]},
  { name: "'Butts'", types: ["normal"]},
  { name: "Weed and/or Snoop Dogg", types: ["normal"]},
  { name: "Messing around with Xsplit", types: ["normal"]},
  { name: "'They probably deserved it.'", types: ["normal"]},
  { name: "Booru plug", types: ["normal"]},
  { name: "Bingo plug", types: ["normal"]},
  { name: "Edutainment game", types: ["normal"]},
  { name: "Girl Game", types: ["normal"]},
  { name: "Tycoon game", types: ["normal"]},
  { name: "Sim(ulator) game", types: ["normal"]},
  { name: "Police sirens in the background", types: ["normal"]},
  { name: "'One (of these) Day(s)...'", types: ["normal"]},
  { name: "Showing off old saves", types: ["normal"]},
  { name: "Bad ending / Game Over", types: ["normal"]},
  { name: "'Whose/What emote is that?'", types: ["normal"]},
  { name: "Strawpoll", types: ["normal"]},
  { name: "Steven Reed / Weber Cooks", types: ["normal"]},
  { name: "Tim complains about his laptop", types: ["normal"]},
  { name: "'Oh Jesus Christ!'", types: ["normal"]},
  { name: "Tim admits to drinking too much coffee/tea", types: ["normal"]},
  { name: "Windows 98/2000/ME", types: ["normal"]},
  { name: "Obama", types: ["normal"]},
  { name: "Closer to the microphone (aka ASMR mode)", types: ["normal"]},
  { name: "MS Paint diagram", types: ["normal"]},
  { name: "Game has been Quick Look'd by Giant Bomb", types: ["normal"]},
  { name: "Tim complains about grad school", types: ["normal"]},
  { name: "15+ minutes without a game (not counting Hold On time)", types: ["normal"]},
  { name: "'I paid money for this.'", types: ["normal"]},
  { name: "'Oh man, could you imagine?'", types: ["normal"]},
  { name: "'I'll take it!'", types: ["normal"]},
  { name: "'OK Google'", types: ["normal"]},
  { name: "Tim ignores the tutorial", types: ["normal"]},
  { name: "Game crash", types: ["normal"]},
  { name: "Tim makes fun of a YouTuber", types: ["normal"]},
  { name: "Anime game", types: ["normal"]},
  { name: "MIDIs", types: ["normal"]},
  { name: "Novelty numbers: 420, 69, or 666", types: ["normal"]},
  { name: "Grandfather clocks outside Oregon Trail", types: ["normal"]},
  { name: "Tim makes a barf noise", types: ["normal"]},
  { name: "Game from the PO box", types: ["normal"]},
  { name: "Geocities (or Reocities)", types: ["normal"]},
  { name: "'Ha ha ugh kill me'", types: ["normal"]},
  { name: "'I have an idea...'", types: ["normal"]},
  { name: "Thomas the Tank Engine", types: ["normal"]},
  { name: "Tim Buckley / CtrlAltDel", types: ["normal"]},
  { name: "'Cyberbullying'", types: ["normal"]},
  { name: "Tim hasn't seen a movie", types: ["normal"]},
  { name: "New Jersey", types: ["normal"]},
  { name: "Florida", types: ["normal"]},
  { name: "Tim pronounces a word weird", types: ["normal"]},
  { name: "'Eh, it happens.'", types: ["normal"]},
  { name: "Baltimore", types: ["normal"]},
  { name: "'Deflated baby'", types: ["normal"]},
  { name: "Poo", types: ["normal"]},
  { name: "'Legitimately'", types: ["normal"]},
  { name: "'That rounds up/down'", types: ["normal"]},
  { name: "Sports _____", types: ["normal"]},
  { name: "London", types: ["normal"]},
  { name: "Tim reads Japanese", types: ["normal"]},
  { name: "WikiHow", types: ["normal"]},
  { name: "Asia Old Man", types: ["normal"]},
];

$(function() { srl.bingo(bingoList, 5); });