var bingoList = [];
bingoList[1] = [
  { name: "Amazon", types: ["normal"]},
  { name: "Cholera", types: ["normal"]},
  { name: "Mr. Bones", types: ["normal"]},
  { name: "Persona reference", types: ["normal"]},
  { name: "Ace Attorney reference", types: ["normal"]},
  { name: "Sonic the Hedgehog reference", types: ["normal"]},
  { name: "'I'm sorry, what!?'", types: ["normal"]},
  { name: "Tim refers to himself as a girl", types: ["normal"]},
  { name: "Tim mimics a character", types: ["normal"]},
  { name: "PICNIC", types: ["normal"]},
  { name: "'Butts'", types: ["normal"]},
  { name: "Weed and/or Snoop Dogg", types: ["normal"]},
  { name: "Messing around with Xsplit", types: ["normal"]},
  { name: "'They probably deserved it.'", types: ["normal"]},
  { name: "Booru plug", types: ["normal"]},
  { name: "Bingo plug", types: ["normal"]},
  { name: "Police sirens in the background", types: ["normal"]},
  { name: "'One day' or 'One of these days...'", types: ["normal"]},
  { name: "Showing off old saves", types: ["normal"]},
  { name: "Bad ending / Game Over", types: ["normal"]},
  { name: "Out of money", types: ["normal"]},
  { name: "Strawpoll", types: ["normal"]},
  { name: "Steven Reed / Weber Cooks", types: ["normal"]},
  { name: "'Oh Jesus Christ!'", types: ["normal"]},
  { name: "Coffee/tea", types: ["normal"]},
  { name: "Obama", types: ["normal"]},
  { name: "Closer to the microphone", types: ["normal"]},
  { name: "MS Paint diagram", types: ["normal"]},
  { name: "Grad school", types: ["normal"]},
  { name: "'I paid money for this.'", types: ["normal"]},
  { name: "'Oh man, could you imagine?'", types: ["normal"]},
  { name: "'I'll take it!'", types: ["normal"]},
  { name: "'Hey Cortana' or 'OK Google'", types: ["normal"]},
  { name: "Game crash", types: ["normal"]},
  { name: "MIDIs", types: ["normal"]},
  { name: "Novelty numbers: 420, 69, or 666", types: ["normal"]},
  { name: "Grandfather clocks", types: ["normal"]},
  { name: "Barf noise", types: ["normal"]},
  { name: "Geocities (or Reocities)", types: ["normal"]},
  { name: "'Ha ha ugh kill me'", types: ["normal"]},
  { name: "'I have an idea...'", types: ["normal"]},
  { name: "Thomas the Tank Engine", types: ["normal"]},
  { name: "'Cyberbullying'", types: ["normal"]},
  { name: "Tim hasn't seen that movie", types: ["normal"]},
  { name: "New Jersey", types: ["normal"]},
  { name: "Tim pronounces a word weird", types: ["normal"]},
  { name: "'Eh, it happens.'", types: ["normal"]},
  { name: "Baltimore", types: ["normal"]},
  { name: "'Deflated baby'", types: ["normal"]},
  { name: "Poo", types: ["normal"]},
  { name: "'Legitimately'", types: ["normal"]},
  { name: "'That rounds up/down'", types: ["normal"]},
  { name: "London", types: ["normal"]},
  { name: "Tim reads Japanese", types: ["normal"]},
  { name: "WikiHow", types: ["normal"]},
  { name: "Asia Old Man", types: ["normal"]},
  { name: "Donald Trump", types: ["normal"]},
  { name: "'This changes everything!'", types: ["normal"]},
  { name: "!sellout plug", types: ["normal"]},
  { name: "FMV", types: ["normal"]},
  { name: "Bathroom break", types: ["normal"]},
  { name: "Reading internet comments", types: ["normal"]},
  { name: "'God, I wish'", types: ["normal"]},
  { name: "2+ 'Oh's in a row", types: ["normal"]},
];

$(function() { srl.bingo(bingoList, 5); });
