var bingoList = [];
bingoList[1] = [
  { name: "Video by Mega64/Robot Chicken/etc", types: ["normal"]},
  { name: "New game in a 'dead' franchise (eg F-Zero)", types: ["normal"]},
  { name: "Any mention of Mother 3 at all whatsoever", types: ["normal"]},
  { name: "Apologizing for amiibo", types: ["normal"]},
  { name: "Nindies", types: ["normal"]},
  { name: "Minigame collection", types: ["normal"]},
  { name: "Retro Studios", types: ["normal"]},
  { name: "Mario sport game", types: ["normal"]},
  { name: "New paid DLC for a released game", types: ["normal"]},
  { name: "Local participating Best Buy", types: ["normal"]},
  { name: "'Please Understand'", types: ["normal"]},
  { name: "Remake", types: ["normal"]},
  { name: "Return of Project Guard or Giant Robot", types: ["normal"]},
  { name: "Sequel to mediocre game nobody wanted", types: ["normal"]},
  { name: "Free-to-play garbage", types: ["normal"]},
  { name: "Yet another Mario amiibo", types: ["normal"]},
  { name: "Mario RPG", types: ["normal"]},
  { name: "'Directly' or the hand motion", types: ["normal"]},
  { name: "New collaboration with another studio", types: ["normal"]},
  { name: "Platinum Games", types: ["normal"]},
  { name: "New system on Virtual Console", types: ["normal"]},
  { name: "Mobile game", types: ["normal"]},
  { name: "Kid Now Squid Now", types: ["normal"]},
  { name: "New Smash character", types: ["normal"]},
  { name: "Mobile app (non-game)", types: ["normal"]},
  { name: "'My body is ready' or similar reference", types: ["normal"]},
  { name: "Animal Crossing game (not the home designer thing)", types: ["normal"]},
  { name: "Year of _____", types: ["normal"]},
  { name: "'New'", types: ["normal"]},
  { name: "Available on the eShop after this presentation", types: ["normal"]},
  { name: "Weird peripheral, new or existing", types: ["normal"]},
  { name: "Cross-buy", types: ["normal"]},
  { name: "Club Nintendo, or replacement", types: ["normal"]},
  { name: "Wario game", types: ["normal"]},
  { name: "Rhythm Heaven 3DS leaving Japan", types: ["normal"]},
];

$(function() { srl.bingo(bingoList, 5); });