var bingoList = [];
bingoList[1] = [
  { name: "First stream in 2+ weeks", types: ["normal"]},
  { name: "Strawpoll crashes", types: ["normal"]},
  { name: "Someone asks about Superman 64", types: ["normal"]},
  { name: "A in-joke name subscribes", types: ["normal"]},
  { name: "Jon glitches a game", types: ["normal"]},
  { name: "3 RPG's picked for 1 cookie", types: ["normal"]},
  { name: "Wheel of Fortune", types: ["normal"]},
  { name: "Bomberman game", types: ["normal"]},
  { name: "Robocop game", types: ["normal"]},
  { name: "Jon plays the wrong sound", types: ["normal"]},
  { name: "Stream starts late", types: ["normal"]},
  { name: "Jurassic park game", types: ["normal"]},
  { name: "4/5 super hard cookie choices", types: ["normal"]},
  { name: "Waluigi in game", types: ["normal"]},
  { name: "Is this game on Wikipedia?", types: ["normal"]},
  { name: "Fortune cookie picks a weird game", types: ["normal"]},
  { name: "FOOTBALL!", types: ["normal"]},
  { name: "Backloggery maintenance when a cookie is needed", types: ["normal"]},
  { name: "Eggs in a game", types: ["normal"]},
  { name: "People spam the nightbot commands", types: ["normal"]},
  { name: "Someone donates a crazy amount of money", types: ["normal"]},
  { name: "5+ subs at once", types: ["normal"]},
  { name: "Kids educational game is played", types: ["normal"]},
  { name: "A sub is missed", types: ["normal"]},
  { name: "Webcam is required", types: ["normal"]},
  { name: "Game is impeached", types: ["normal"]},
  { name: "ROM hack reference", types: ["normal"]},
  { name: "Convention story", types: ["normal"]},
  { name: "Incoming long trip", types: ["normal"]},
  { name: "Oh my god! What the actual F***?", types: ["normal"]},
  { name: "A game Jon hates is picked", types: ["normal"]},
  { name: "Barbie", types: ["normal"]},
  { name: "Someone asks about Yoshi's Island", types: ["normal"]},
  { name: "Selected game won't start", types: ["normal"]},
];

$(function() { srl.bingo(bingoList, 5); });